apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdavid
  namespace: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxdavid
  template:
    metadata:
      labels:
        app: nginxdavid
    spec:
      containers:
        - name: nginxdavid
          image: daviddeif/nginx:vtag
          imagePullPolicy: IfNotPresent
          ports:
            - name: httpport
              containerPort: 80
              protocol: TCP


        
