apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      initContainers:
        - name: install-docker
          image: docker:stable
          command: ["cp","/usr/local/bin/docker", "/opt/temp1"]
          volumeMounts:  
            - name: docker
              mountPath: /opt/temp1

        - name: install-kubectl
          image: alpine/k8s:1.23.13
          command: ["cp","/usr/bin/kubectl","/opt/temp2"]
          volumeMounts:
            - name: kubectl
              mountPath: "/opt/temp2"

      containers:
        - name: jenkins
          image: daviddeif/jenkins_with_gcloud:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: httpport
              containerPort: 8080
              protocol: TCP	
            - name: jnlpport
              containerPort: 50000
              protocol: TCP

          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home

            - name: dockersock
              mountPath: /var/run/
            
            - name: docker
              mountPath: /usr/bin/docker
              subPath: docker

            - name: kubectl
              mountPath: /usr/bin/kubectl
              subPath: kubectl

        
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
           claimName: pvc-demo

        - name: docker
          emptyDir: {}
        
        - name: dockersock
          hostPath:
            path: /var/run/

        - name: kubectl
          emptyDir: {}
        
